---
type: Asset
api_version: core/v2
metadata:
  name: ruby-hello-world-shebang
  namespace: default
  labels: {}
  annotations: {}
spec:
  url: http://sensu-asset-server/assets/hello-world-ruby.tar.gz
  sha512: 8e5979ccf6d3d57e0c8235fc71079922dd870f2022b47bc6f96796a716c51a9824c3785fce25e6dbc5d792d2a62525d8f0a975c6bac002238991d22b974cd60e
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
