---
type: Asset
api_version: core/v2
metadata:
  name: ruby-hello-world 
  namespace: default
  labels: {}
  annotations: {}
spec:
  url: http://sensu-asset-server/assets/helloworld-v0.1.tar.gz
  sha512: a7439442c9c5ebe47ea9d4f575ca2850bfc4fd3ee61f3a61430e025e3175a45e5c7c464b69558821c54714d55dc216de167b4db29db4984cfc814241b6e42387
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'

