---
type: Asset
api_version: core/v2
metadata:
  name: sensu-ruby-runtime
  namespace: default
  labels: {}
  annotations: {}
spec:
  url: http://sensu-asset-server/assets/sensu-ruby-runtime_0.0.5_alpine_linux_amd64.tar.gz
  sha512: dc4c60215c8606062609b471d803147045a6855ccf55d4d3145d96ca528fac48a3b039a1563e4de65b9c9a9fb09445f3a133a6ab1a4d688c1b8164b1b1ba799d
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'

