---
type: CheckConfig
api_version: core/v2
metadata:
  name: hello-world-ruby-shebang
  namespace: default
  labels: {}
  annotations: {}
spec:
  command: "helloworld.rb"
  runtime_assets:
  - ruby-hello-world-shebang
  - sensu-ruby-runtime
  publish: true
  interval: 10
  subscriptions:
  - dev